language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  pytest
env:
  - ENV_DIR=$TRAVIS_BUILD_DIR
notifications: 
  slack: raz-s:se1PurXsQJv03nBZa9XWMOOS
