language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r tests/requirements.txt
- pip install -r requirements.txt
- python setup.py install
script:
- python setup.py check -rms
- flake8
- pytest
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  skip_existing: true
  skip_cleanup: true
  user: __token__
  on:
    tags: true
    branch: master
  password:
    secure: Gn76cUt/aT0FF7AV7w2Q3d8SZpNZwL/HSw5NqsOm9NtihG2Z+3mOrfeSL9f1tX1dsyCP3NGZ6EKgdBW0wYnkpvUTw3/Ab2a0siLqqbUDobgb58X+Xdu2gkWXrp6uPnNcL6SqATGgdrR/DP2zRDv4KCRTWT/VOsMHBsoOUHS7Zj1UNkFlGqPyPGYoD4XUNNa9VREG0tD89Ig1pml2cwF3rt0nLr4Yaojy0IiMcGcSK+FGL57QIfJvJWnnN2SN5HkzsY7B8v/IGO69vXTHREV3tMTU+6sErgKp/7ObIwlCRCZZ5fML1T34MC/KZRrWbJuZQg2PoCmG56opemlBEUpwA4PZzCqDCAHNEXX6TCoUbKtL6Ys/d6yNJv/FNc1xAr4sLfBLWSbC2Abbky60hPkTeya1poLCGZbJVaeuUP92zYUAdr/4LQIq3pSvNXraXVzNYlNGwDujxvxWpzmFFxuifPxFgpKL20n/x6iHofsAGvglTjfHiVoGjG/v2qJWrvgW1e7aUrH/K8G5i9/e1G/7q3I8JhYuK4DwONW1frT6FoFHxkA5CE5EaOkATl0zPQtl1tEuF6MnqTsBfcoBocTZKNGGuuLCDLoT3P5WWDA01GjWG+4Ym0jz+YV4tqcHfXBrcaOak9BmnFQ8MHSEC+X+GnWTm/mTiW8Mt6CqBN18J/s=
