language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r tests/requirements.txt
- pip install -r requirements.txt
- python setup.py install
script:
- python setup.py check -rms
- flake8
- pytest
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  skip_existing: true
  skip_cleanup: true
  user: __token__
  on:
    tags: true
    branch: master
  password:
    secure: euM8fmnjTHmzumtt5692yI6IlZWP3+CtsXsdOJ3ajmN+lJvydWyXKj8ZM7vgyHA7xuVTr6G+x6/nJ0F5DwwLi6iGdnBeJTF7IkqwiK3P6Kz4lK4uyez+SeDSayTea55/2ZxFOHvbt5KJHmeWIwSVvqXqVWBeBtr72atkWeiVWk/xWR+lLEtQ1WaDGEegmRKBaFoCkzk6EYz2AfuzSV/CfhLfVXUQtkJ0OXSNLO5q5dHsD6fnBnHHB29kQj7X24sXNfQLQLLaLQs0UG9U7iBgMPuFJZ//R+xKV/HjnYjaV1LGdgf7zdwEcPAr+7/Anb6+F4/YaEskzMJds/VpkY82cLestHVBt64xfAfG3iPirkkDKEacX4TwKsXbQxMt/nsZ2mB/N5DXZm+YKz4m7YBZHHVrBYLu2a0Pdn7tn/nfJ3zIAyAnSaJHquB+n1hMuSOl0cIA8wmyt6C3pGQBszVeeQTlg64Hjm0X9uNS7zcphrs9hH9FnDmHbmau1yinJWB2qx8RpYjP2Uu9wxWMwTNbn9ZnW/3lC3hslGHQow1+D1gIOfB7Doh1vYgnW9IK2C6VOfSVpNgI2YfOv78pnjbTY5xq14aBOa7wTXCc+T2vkOL0W3F0I/mdQxk0YQ5Od8GX7+FBzX4wbE5vSkV9ZTVr2EF/ChnGbbqTpRtDlhWGFIU=
