language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r tests/requirements.txt
- pip install -r requirements.txt
- python setup.py install
script:
- python setup.py check -rms
- flake8
- pytest
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  skip_existing: true
  skip_cleanup: true
  user: __token__
  on:
    tags: true
    branch: master
