version: '3.7'

services:
  web:
    image: nielsbohr/escience-projects:latest
    container_name: escience-projects
    ports:
      - "80:80/tcp"
    volumes:
      - ./persistence:/var/escience-projects/persistence:rw
      - ./res:/etc/escience-projects/res:ro
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro