version: '3.7'

services:
  web:
    image: nielsbohr/projects:latest
    container_name: projects
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./persistence:/var/projects/persistence
      - ./well-known:/var/www/public/well-known
      - ./certs:/var/www/certs
