version: '3.7'

# Only use this stack for development or debugging,
# A WSGI stack should be used for production (docker-compose.yml)
services:
  web:
    image: nielsbohr/escience-projects:edge
    container_name: escience-projects
    ports:
      - "80:80/tcp"
    volumes:
      - ./persistence:/var/escience-projects/persistence:rw
      - ./res:/etc/escience-projects/res:ro
      - ./supervisord-debug.conf:/etc/supervisor/conf.d/supervisord.conf:ro